//HintName: SealedFgaInit.g.cs
// <auto-generated>
//     This file was generated by SealedFga. Do not edit it directly.
// </auto-generated>
#nullable enable

using SealedFga.Util;

namespace SealedFga;

/// <summary>
///     SealedFga static class for initialization and registration of SealedFGA type IDs.
/// </summary>
public static class SealedFgaInit {
    /// <summary>
    ///     Initializes the SealedFga library by registering all SealedFGA type IDs.
    /// </summary>
    public static void Initialize() {
        // Register all SealedFGA type IDs.
        IdUtil.RegisterIdType(typeof(TestApp.SecretEntityId), "secret");
        IdUtil.RegisterIdTypeParseMethod(typeof(TestApp.SecretEntityId), TestApp.SecretEntityId.Parse);
        IdUtil.RegisterIdType(typeof(TestApp.AgencyEntityId), "agency");
        IdUtil.RegisterIdTypeParseMethod(typeof(TestApp.AgencyEntityId), TestApp.AgencyEntityId.Parse);

    }
}