//HintName: SecretEntityId.partial.g.cs
// <auto-generated>
//     This file was generated by SealedFga. Do not edit it directly.
// </auto-generated>
#nullable enable

using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SealedFga.AuthModel;
using SealedFga.Util;
using System.ComponentModel;
using System.Text.Json.Serialization;
using System;

namespace TestApp;


/// <remarks>
///     As a value type, <c>default(SecretEntityId)</c> is representable and carries the
///     all-zero value (<c>Guid.Empty</c>). It never denotes an existing entity;
///     don't let uninitialized IDs flow into tuples or queries.
/// </remarks>
[TypeConverter(typeof(IdTypeConverter))]
[JsonConverter(typeof(IdJsonConverter))]
public readonly partial record struct SecretEntityId : ISealedFgaTypeId<SecretEntityId>
{
    /// <summary>
    ///     The ID's value.
    /// </summary>
    public Guid Value { get; }

    /// <summary>
    ///     Creates a new instance of SecretEntityId from the ID's "raw" type.
    /// </summary>
    /// <param name="val">The raw ID's value.</param>
    public SecretEntityId(Guid val)
    {
        Value = val;
    }

    /// <inheritdoc />
    public static string OpenFgaTypeName => "secret";

    /// <summary>
    ///     Creates a new instance of <see cref="SecretEntityId"/> with a generated value.
    /// </summary>
    public static SecretEntityId New()
    {
        return new SecretEntityId(Guid.NewGuid());
    }

    /// <inheritdoc />
    public static SecretEntityId Parse(string val)
    {
        return new SecretEntityId(Guid.Parse(val));
    }

    /// <inheritdoc />
    public string AsOpenFgaIdTupleString()
        => $"{OpenFgaTypeName}:{ToString()}";

    /// <inheritdoc />
    public override string ToString()
    {
        return Value.ToString();
    }

    /// <summary>
    ///     Converts a <see cref="SecretEntityId" /> to a <see cref="Guid" /> and vice versa for DB storage.
    /// </summary>
    public class EfCoreValueConverter() : ValueConverter<SecretEntityId, Guid>(
        id => id.Value,
        val => new SecretEntityId(val));

    /// <summary>
    ///    Converts a <see cref="SecretEntityId" /> to its JSON representation and vice versa.
    /// </summary>
    public class IdJsonConverter() : JsonSimpleStringConverter<SecretEntityId>(s => SecretEntityId.Parse(s));

    /// <summary>
    ///    Converts a <see cref="SecretEntityId" /> to another compatible type and vice versa.
    /// </summary>
    public class IdTypeConverter() : GuidIdTypeConverter<SecretEntityId>(g => new SecretEntityId(g), s => SecretEntityId.Parse(s));
}