//HintName: SealedFgaInit.g.cs
// <auto-generated>
//     This file was generated by SealedFga. Do not edit it directly.
// </auto-generated>
#nullable enable

using SealedFga.Util;
using System.Runtime.CompilerServices;

namespace SealedFga;

/// <summary>
///     SealedFga static class for initialization and registration of SealedFGA type IDs.
/// </summary>
public static class SealedFgaInit {
    /// <summary>
    ///     Runs <see cref="Initialize" /> automatically when the consumer assembly is loaded,
    ///     so consumers never have to call it themselves. Kept separate (and internal) from
    ///     the public <see cref="Initialize" /> so tests can still register test-only IDs by
    ///     calling <see cref="Initialize" /> directly (registration is idempotent).
    /// </summary>
    [ModuleInitializer]
    internal static void AutoInitialize() => Initialize();

    /// <summary>
    ///     Initializes the SealedFga library by registering all SealedFGA type IDs.
    /// </summary>
    public static void Initialize() {
        // Register all SealedFGA type IDs.
        IdUtil.RegisterIdType(typeof(TestApp.GhostEntityId), "does_not_exist");
        IdUtil.RegisterIdTypeParseMethod(typeof(TestApp.GhostEntityId), TestApp.GhostEntityId.Parse);

    }
}