//HintName: SecretEntityIdAttributes.g.cs
// <auto-generated>
//     This file was generated by SealedFga. Do not edit it directly.
// </auto-generated>
#nullable enable

using SealedFga.AuthModel;
using SealedFga;

namespace TestApp;

/// <summary>
///     Represents a set of strongly-typed SealedFGA relations for the SecretEntityIdAttributes entity.
/// </summary>
public class SecretEntityIdAttributes(string val)
: SealedFgaRelation(val), ISealedFgaRelation<SecretEntityId>
{
    public static readonly SecretEntityIdAttributes can_view = new SecretEntityIdAttributes("can_view");


    /// <summary>
    ///     Creates a <see cref="SecretEntityIdAttributes"/> from an OpenFGA relation string.
    /// </summary>
    /// <param name="openFgaString">The OpenFGA relation string.</param>
    /// <returns>A new <see cref="SecretEntityIdAttributes"/> instance.</returns>
    public static SecretEntityIdAttributes FromOpenFgaString(string openFgaString) => new SecretEntityIdAttributes(openFgaString);
}