//HintName: SecretEntityIdPermissions.g.cs
// <auto-generated>
//     This file was generated by SealedFga. Do not edit it directly.
// </auto-generated>
#nullable enable

using SealedFga.AuthModel;
using SealedFga;

namespace TestApp;

/// <summary>
///     Represents a set of strongly-typed SealedFGA relations for the SecretEntityIdPermissions entity.
/// </summary>
public class SecretEntityIdPermissions(string val)
: SealedFgaRelation(val), ISealedFgaRelation<SecretEntityId>
{
    /// <summary>The <c>can_view</c> relation.</summary>
    public static readonly SecretEntityIdPermissions can_view = new SecretEntityIdPermissions("can_view");


    /// <summary>
    ///     Creates a <see cref="SecretEntityIdPermissions"/> from an OpenFGA relation string.
    /// </summary>
    /// <param name="openFgaString">The OpenFGA relation string.</param>
    /// <returns>A new <see cref="SecretEntityIdPermissions"/> instance.</returns>
    public static SecretEntityIdPermissions FromOpenFgaString(string openFgaString) => new SecretEntityIdPermissions(openFgaString);
}