//HintName: SecretEntityIncludes.g.cs
// <auto-generated>
//     This file was generated by SealedFga. Do not edit it directly.
// </auto-generated>
#nullable enable


namespace TestApp;

/// <summary>
///     Valid navigation properties that can be eager-loaded (EF Include) for SecretEntity.
/// </summary>
public static class SecretEntityIncludes
{
    public const string OwningAgency = "OwningAgency";
    public const string RelatedAgencies = "RelatedAgencies";

}