//HintName: SecretEntityId.partial.g.cs
// <auto-generated>
//     This file was generated by SealedFga. Do not edit it directly.
// </auto-generated>
#nullable enable

using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SealedFga.AuthModel;
using SealedFga.Util;
using System.ComponentModel;
using System.Globalization;
using System.Text.Json.Serialization;
using System;

namespace TestApp;


/// <remarks>
///     As a value type, <c>default(SecretEntityId)</c> is representable and carries the
///     all-zero value (<c>0</c>). It never denotes an existing entity;
///     don't let uninitialized IDs flow into tuples or queries.
/// </remarks>
[TypeConverter(typeof(IdTypeConverter))]
[JsonConverter(typeof(IdJsonConverter))]
public readonly partial record struct SecretEntityId : ISealedFgaTypeId<SecretEntityId>
{
    /// <summary>
    ///     The ID's value.
    /// </summary>
    public int Value { get; }

    /// <summary>
    ///     Creates a new instance of SecretEntityId from the ID's "raw" type.
    /// </summary>
    /// <param name="val">The raw ID's value.</param>
    public SecretEntityId(int val)
    {
        Value = val;
    }

    /// <inheritdoc />
    public static string OpenFgaTypeName => "secret";

    // No New() is generated for integer-backed IDs: their values are database-assigned
    // (identity); a synthetic value such as 0 would be a dangerous "unset" ID.

    /// <inheritdoc />
    public static SecretEntityId Parse(string val)
    {
        return new SecretEntityId(int.Parse(val, CultureInfo.InvariantCulture));
    }

    /// <inheritdoc />
    public string AsOpenFgaIdTupleString()
        => $"{OpenFgaTypeName}:{ToString()}";

    /// <inheritdoc />
    public override string ToString()
    {
        return Value.ToString(CultureInfo.InvariantCulture);
    }

    /// <summary>
    ///     Converts a <see cref="SecretEntityId" /> to a <see cref="int" /> and vice versa for DB storage.
    /// </summary>
    public class EfCoreValueConverter() : ValueConverter<SecretEntityId, int>(
        id => id.Value,
        val => new SecretEntityId(val));

    /// <summary>
    ///    Converts a <see cref="SecretEntityId" /> to its JSON representation and vice versa.
    /// </summary>
    public class IdJsonConverter() : JsonSimpleInt32Converter<SecretEntityId>(v => new SecretEntityId(v), id => id.Value);

    /// <summary>
    ///    Converts a <see cref="SecretEntityId" /> to another compatible type and vice versa.
    /// </summary>
    public class IdTypeConverter() : Int32IdTypeConverter<SecretEntityId>(v => new SecretEntityId(v), s => SecretEntityId.Parse(s), id => id.Value);
}