//HintName: AgencyEntityId.partial.g.cs
// <auto-generated>
//     This file was generated by SealedFga. Do not edit it directly.
// </auto-generated>
#nullable enable

using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SealedFga.AuthModel;
using SealedFga.Util;
using System.ComponentModel;
using System.Text.Json.Serialization;
using System;

namespace TestApp;


/// <remarks>
///     As a value type, <c>default(AgencyEntityId)</c> is representable and carries the
///     all-zero value (<c>Guid.Empty</c>). It never denotes an existing entity;
///     don't let uninitialized IDs flow into tuples or queries.
/// </remarks>
[TypeConverter(typeof(IdTypeConverter))]
[JsonConverter(typeof(IdJsonConverter))]
public readonly partial record struct AgencyEntityId : ISealedFgaTypeId<AgencyEntityId>
{
    /// <summary>
    ///     The ID's value.
    /// </summary>
    public Guid Value { get; }

    /// <summary>
    ///     Creates a new instance of AgencyEntityId from the ID's "raw" type.
    /// </summary>
    /// <param name="val">The raw ID's value.</param>
    public AgencyEntityId(Guid val)
    {
        Value = val;
    }

    /// <inheritdoc />
    public static string OpenFgaTypeName => "agency";

    /// <summary>
    ///     Creates a new instance of <see cref="AgencyEntityId"/> with a generated value.
    /// </summary>
    public static AgencyEntityId New()
    {
        return new AgencyEntityId(Guid.NewGuid());
    }

    /// <inheritdoc />
    public static AgencyEntityId Parse(string val)
    {
        return new AgencyEntityId(Guid.Parse(val));
    }

    /// <inheritdoc />
    public string AsOpenFgaIdTupleString()
        => $"{OpenFgaTypeName}:{ToString()}";

    /// <inheritdoc />
    public override string ToString()
    {
        return Value.ToString();
    }

    /// <summary>
    ///     Converts a <see cref="AgencyEntityId" /> to a <see cref="Guid" /> and vice versa for DB storage.
    /// </summary>
    public class EfCoreValueConverter() : ValueConverter<AgencyEntityId, Guid>(
        id => id.Value,
        val => new AgencyEntityId(val));

    /// <summary>
    ///    Converts a <see cref="AgencyEntityId" /> to its JSON representation and vice versa.
    /// </summary>
    public class IdJsonConverter() : JsonSimpleStringConverter<AgencyEntityId>(s => AgencyEntityId.Parse(s));

    /// <summary>
    ///    Converts a <see cref="AgencyEntityId" /> to another compatible type and vice versa.
    /// </summary>
    public class IdTypeConverter() : GuidIdTypeConverter<AgencyEntityId>(g => new AgencyEntityId(g), s => AgencyEntityId.Parse(s));
}