//HintName: SecretEntityIdRelations.g.cs
// <auto-generated>
//     This file was generated by SealedFga. Do not edit it directly.
// </auto-generated>
#nullable enable

using SealedFga.AuthModel;
using SealedFga;

namespace TestApp;

/// <summary>
///     Represents a set of strongly-typed SealedFGA relations for the SecretEntityIdRelations entity.
/// </summary>
public class SecretEntityIdRelations(string val)
: SealedFgaRelation(val), ISealedFgaRelation<SecretEntityId>
{
    /// <summary>The <c>OwnedBy</c> relation.</summary>
    public static readonly SecretEntityIdRelations OwnedBy = new SecretEntityIdRelations("OwnedBy");
    /// <summary>The <c>can_view</c> relation.</summary>
    public static readonly SecretEntityIdRelations can_view = new SecretEntityIdRelations("can_view");


    /// <summary>
    ///     Creates a <see cref="SecretEntityIdRelations"/> from an OpenFGA relation string.
    /// </summary>
    /// <param name="openFgaString">The OpenFGA relation string.</param>
    /// <returns>A new <see cref="SecretEntityIdRelations"/> instance.</returns>
    public static SecretEntityIdRelations FromOpenFgaString(string openFgaString) => new SecretEntityIdRelations(openFgaString);
}