//HintName: UserEntityId.partial.g.cs
// <auto-generated>
//     This file was generated by SealedFga. Do not edit it directly.
// </auto-generated>
#nullable enable

using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SealedFga.AuthModel;
using SealedFga.Util;
using System.ComponentModel;
using System.Text.Json.Serialization;
using System;

namespace TestApp;


/// <remarks>
///     As a value type, <c>default(UserEntityId)</c> is representable and carries the
///     all-zero value (a <c>null</c> string; <c>ToString()</c> maps it to <c>""</c>). It never denotes an existing entity;
///     don't let uninitialized IDs flow into tuples or queries.
/// </remarks>
[TypeConverter(typeof(IdTypeConverter))]
[JsonConverter(typeof(IdJsonConverter))]
public readonly partial record struct UserEntityId : ISealedFgaTypeId<UserEntityId>
{
    /// <summary>
    ///     The ID's value.
    /// </summary>
    public string Value { get; }

    /// <summary>
    ///     Creates a new instance of UserEntityId from the ID's "raw" type.
    /// </summary>
    /// <param name="val">The raw ID's value.</param>
    public UserEntityId(string val)
    {
        Value = val;
    }

    /// <inheritdoc />
    public static string OpenFgaTypeName => "user";

    /// <summary>
    ///     Creates a new instance of <see cref="UserEntityId"/> with a generated value.
    /// </summary>
    public static UserEntityId New()
    {
        return new UserEntityId("");
    }

    /// <inheritdoc />
    public static UserEntityId Parse(string val)
    {
        return new UserEntityId(val);
    }

    /// <inheritdoc />
    public string AsOpenFgaIdTupleString()
        => $"{OpenFgaTypeName}:{ToString()}";

    /// <inheritdoc />
    public override string ToString()
    {
        return Value ?? "";
    }

    /// <summary>
    ///     Converts a <see cref="UserEntityId" /> to a <see cref="string" /> and vice versa for DB storage.
    /// </summary>
    public class EfCoreValueConverter() : ValueConverter<UserEntityId, string>(
        id => id.Value,
        val => new UserEntityId(val));

    /// <summary>
    ///    Converts a <see cref="UserEntityId" /> to its JSON representation and vice versa.
    /// </summary>
    public class IdJsonConverter() : JsonSimpleStringConverter<UserEntityId>(s => UserEntityId.Parse(s));

    /// <summary>
    ///    Converts a <see cref="UserEntityId" /> to another compatible type and vice versa.
    /// </summary>
    public class IdTypeConverter() : StringIdTypeConverter<UserEntityId>(s => UserEntityId.Parse(s));
}