//HintName: SealedFgaExtensions.g.cs
// <auto-generated>
//     This file was generated by SealedFga. Do not edit it directly.
// </auto-generated>
#nullable enable

using Microsoft.AspNetCore.Builder;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection.Extensions;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Options;
using OpenFga.Sdk.Client;
using SealedFga.Attributes;
using SealedFga.Fga.Outbox;
using SealedFga.Fga;
using SealedFga.Middleware;
using SealedFga.ModelBinder;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System;

namespace SealedFga;


/// <summary>
///     Contains all extension methods the SealedFga library provides/uses.
/// </summary>
public static class SealedFgaExtensions {
    /// <summary>
    ///    Retrieves all SealedFGA ID types from the assembly.
    /// </summary>
    private static IEnumerable<Type> GetSealedFgaIdTypes() {
        var assembly = Assembly.GetExecutingAssembly();
        var idTypes = assembly.GetTypes()
                              .Where(t => t.GetCustomAttribute<SealedFgaTypeIdAttribute>() is not null);

        return idTypes;
    }

    /// <summary>
    ///     Registers the generated EF Core value converters for all SealedFGA ID types.
    ///     Call this from your DbContext's <c>ConfigureConventions</c> override. This has to
    ///     run in the pre-convention phase (not a model customizer): EF Core must know these
    ///     CLR types are converted scalars before relationship discovery, otherwise it treats
    ///     them as entity types.
    /// </summary>
    public static void ConfigureSealedFga(this ModelConfigurationBuilder configurationBuilder) {
        // Retrieve all SealedFGA ID Types from the assembly
        var idTypes = GetSealedFgaIdTypes();

        // Retrieve contained EF Core ValueConverter classes and register them
        foreach (var type in idTypes) {
            var valueConverters = type.GetNestedTypes().Where(t => t.IsSubclassOf(typeof(ValueConverter)));
            foreach (var valueConverter in valueConverters) {
                configurationBuilder
                   .Properties(type)
                   .HaveConversion(valueConverter);
            }
        }
    }

    /// <summary>
    ///     Configures SealedFGA services, binding <see cref="SealedFgaOptions" /> from the
    ///     <c>"SealedFga"</c> configuration section (ApiUrl / StoreId / AuthorizationModelId /
    ///     UserClaimType) and registering an <c>OpenFgaClient</c> from those values.
    /// </summary>
    /// <param name="services">The service collection to configure.</param>
    /// <param name="configuration">Application configuration to bind the options from.</param>
    /// <param name="configure">Optional overrides applied on top of the bound options.</param>
    /// <returns>The service collection for method chaining.</returns>
    public static IServiceCollection ConfigureSealedFga<TDbContext>(
        this IServiceCollection services,
        IConfiguration configuration,
        Action<SealedFgaOptions>? configure = null
    ) where TDbContext : DbContext
    {
        services.AddOptions<SealedFgaOptions>().Bind(configuration.GetSection("SealedFga"));
        return services.ConfigureSealedFga<TDbContext>(configure);
    }

    /// <summary>
    ///     Configures SealedFGA services with the specified options.
    /// </summary>
    /// <param name="services">The service collection to configure.</param>
    /// <param name="configure">Optional configuration action for SealedFgaOptions.</param>
    /// <returns>The service collection for method chaining.</returns>
    public static IServiceCollection ConfigureSealedFga<TDbContext>(
        this IServiceCollection services,
        Action<SealedFgaOptions>? configure = null
    ) where TDbContext : DbContext
    {
        services.AddScoped<SealedFgaService>();
        services.AddScoped<SealedFgaSaveChangesInterceptor>();
        services.AddHostedService<SealedFgaOutboxHostedService<TDbContext>>();
        services.AddControllers(options => {
                options.ModelBinderProviders.Insert(0, new SealedFgaModelBinderProvider<TDbContext>());
            }
        );

        // Always register the options so IOptions<SealedFgaOptions> resolves (to defaults
        // when no configure action is supplied); SealedFgaService depends on it.
        services.AddOptions<SealedFgaOptions>();
        if (configure != null) {
            services.Configure(configure);
        }

        // Register the OpenFgaClient from the resolved options unless the consumer already
        // registered their own (e.g. to supply custom credentials / HTTP handlers).
        services.TryAddSingleton<OpenFgaClient>(sp => {
            var options = sp.GetRequiredService<IOptions<SealedFgaOptions>>().Value;
            var apiUrl = options.ApiUrl
                ?? throw new InvalidOperationException(
                    "SealedFga:ApiUrl is not configured. Set it in the \"SealedFga\" configuration "
                    + "section, via ConfigureSealedFga(o => o.ApiUrl = ...), or register your own "
                    + "OpenFgaClient before calling ConfigureSealedFga.");
            return new OpenFgaClient(new ClientConfiguration {
                ApiUrl = apiUrl,
                StoreId = options.StoreId,
                AuthorizationModelId = options.AuthorizationModelId,
            });
        });

        return services;
    }

    /// <summary>
    ///     Adds all SealedFga DB related options.
    /// </summary>
    public static DbContextOptionsBuilder AddSealedFga(
        this DbContextOptionsBuilder options,
        IServiceProvider serviceProvider
    ) {
        var interceptor = serviceProvider.GetRequiredService<SealedFgaSaveChangesInterceptor>();
        options.AddInterceptors(interceptor);

        // Auto-register the SealedFGA outbox entity into the model without the consumer
        // having to touch their OnModelCreating.
        options.ReplaceService<IModelCustomizer, SealedFgaModelCustomizer>();

        return options;
    }

    /// <summary>
    ///     Adds the SealedFga middleware to the web application.
    /// </summary>
    public static IApplicationBuilder UseSealedFga(this IApplicationBuilder app) {
        app.UseMiddleware<SealedFgaExceptionHandlerMiddleware>();

        return app;
    }
}