//HintName: UserEntityId.partial.g.cs
// <auto-generated>
//     This file was generated by SealedFga. Do not edit it directly.
// </auto-generated>
#nullable enable

using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SealedFga.AuthModel;
using SealedFga.Util;
using System.ComponentModel;
using System.Text.Json.Serialization;
using System;

namespace TestApp;


[TypeConverter(typeof(IdTypeConverter))]
[JsonConverter(typeof(IdJsonConverter))]
public partial class UserEntityId : ISealedFgaTypeId<UserEntityId>, IEquatable<UserEntityId>
{
    /// <summary>
    ///     The ID's value.
    /// </summary>
    public string Value { get; set; }

    /// <summary>
    ///     Creates a new instance of UserEntityId from the ID's "raw" type.
    /// </summary>
    /// <param name="val">The raw ID's value.</param>
    public UserEntityId(string val)
    {
        Value = val;
    }

    /// <inheritdoc />
    public static string OpenFgaTypeName => "user";

    /// <summary>
    ///     Creates a new instance of <see cref="UserEntityId"/> with a generated value.
    /// </summary>
    public static UserEntityId New()
    {
        return new UserEntityId("");
    }

    /// <inheritdoc />
    public static UserEntityId Parse(string val)
    {
        return new UserEntityId(val);
    }

    /// <inheritdoc />
    public string AsOpenFgaIdTupleString()
        => $"{OpenFgaTypeName}:{ToString()}";

    /// <inheritdoc />
    public override string ToString()
    {
        return Value.ToString();
    }

    /// <inheritdoc />
    public override bool Equals(object? obj)
    {
        if (ReferenceEquals(null, obj)) return false;
        if (ReferenceEquals(this, obj)) return true;
        if (obj.GetType() != this.GetType()) return false;
        return Equals((UserEntityId) obj);
    }

    /// <inheritdoc />
    public bool Equals(UserEntityId? other)
    {
        if (ReferenceEquals(null, other)) return false;
        if (ReferenceEquals(this, other)) return true;
        return Value.Equals(other.Value);
    }

    /// <inheritdoc />
    public override int GetHashCode()
    {
        return Value.GetHashCode();
    }

    public static bool operator ==(UserEntityId? left, UserEntityId? right)
    {
        if (ReferenceEquals(left, null))
        {
            return ReferenceEquals(right, null);
        }

        return left.Equals(right);
    }

    public static bool operator !=(UserEntityId? left, UserEntityId? right)
    {
        return !(left == right);
    }


    /// <summary>
    ///     Converts a <see cref="UserEntityId" /> to a <see cref="string" /> and vice versa for DB storage.
    /// </summary>
    public class EfCoreValueConverter() : ValueConverter<UserEntityId, string>(
        id => id.Value,
        val => new UserEntityId(val));

    /// <summary>
    ///    Converts a <see cref="UserEntityId" /> to its JSON representation and vice versa.
    /// </summary>
    public class IdJsonConverter() : JsonSimpleStringConverter<UserEntityId>(s => UserEntityId.Parse(s));

    /// <summary>
    ///    Converts a <see cref="UserEntityId" /> to another compatible type and vice versa.
    /// </summary>
    public class IdTypeConverter() : StringIdTypeConverter<UserEntityId>(s => UserEntityId.Parse(s));
}