//HintName: SealedFgaCheckDispatch.g.cs
// <auto-generated>
//     This file was generated by SealedFga. Do not edit it directly.
// </auto-generated>
#nullable enable

using SealedFga.AuthModel;
using SealedFga.Fga;
using System.Threading.Tasks;
using System.Threading;

namespace SealedFga;

/// <summary>
///     Generated dispatcher for the "check any permission on any object type" surface. Maps an
///     OpenFGA type name to the strongly-typed <see cref="ISealedFgaService.CheckAsync{TObjId}" />
///     call for that type, so callers with a stringly-typed request do not hand-maintain a switch.
/// </summary>
public static class SealedFgaCheckDispatch {
    /// <summary>
    ///     Checks <paramref name="relation" /> for <paramref name="user" /> against the object
    ///     <c>{typeName}:{objectId}</c>, dispatching on <paramref name="typeName" /> to the
    ///     strongly-typed check for that type. The typed call path is preserved (not a raw tuple
    ///     string) so any ambient options provider — e.g. a super-user contextual tuple — still
    ///     applies. Returns <c>null</c> when <paramref name="typeName" /> is not a known checkable
    ///     SealedFGA type; the caller typically maps that to a 400.
    /// </summary>
    /// <param name="svc">The SealedFGA service to check against.</param>
    /// <param name="user">The user/subject being checked.</param>
    /// <param name="typeName">The object's OpenFGA type name (e.g. <c>"charger"</c>).</param>
    /// <param name="relation">The relation/permission to check (e.g. <c>"can_view"</c>).</param>
    /// <param name="objectId">The object's raw ID (parsed into the type's strongly-typed ID).</param>
    /// <param name="queryOptions">Optional per-call options (contextual tuples, consistency).</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns><c>true</c>/<c>false</c> for the check, or <c>null</c> for an unknown type name.</returns>
    public static async Task<bool?> TryCheckByTypeNameAsync(
        this ISealedFgaService svc,
        ISealedFgaUser user,
        string typeName,
        string relation,
        string objectId,
        SealedFgaQueryOptions? queryOptions = null,
        CancellationToken cancellationToken = default
    ) => typeName switch {
            "agency" => await svc.CheckAsync(user, TestApp.AgencyEntityIdGroups.FromOpenFgaString(relation), TestApp.AgencyEntityId.Parse(objectId), queryOptions, cancellationToken),

            _ => null,
        };
}