//HintName: AgencyEntityIdGroups.g.cs
// <auto-generated>
//     This file was generated by SealedFga. Do not edit it directly.
// </auto-generated>
#nullable enable

using SealedFga.AuthModel;
using SealedFga;

namespace TestApp;

/// <summary>
///     Represents a set of strongly-typed SealedFGA relations for the AgencyEntityIdGroups entity.
/// </summary>
public class AgencyEntityIdGroups(string val)
: SealedFgaRelation(val), ISealedFgaRelation<AgencyEntityId>
{
    public static readonly AgencyEntityIdGroups Member = new AgencyEntityIdGroups("Member");


    /// <summary>
    ///     Creates a <see cref="AgencyEntityIdGroups"/> from an OpenFGA relation string.
    /// </summary>
    /// <param name="openFgaString">The OpenFGA relation string.</param>
    /// <returns>A new <see cref="AgencyEntityIdGroups"/> instance.</returns>
    public static AgencyEntityIdGroups FromOpenFgaString(string openFgaString) => new AgencyEntityIdGroups(openFgaString);
}