//HintName: SecretEntityIdGroups.g.cs
// <auto-generated>
//     This file was generated by SealedFga. Do not edit it directly.
// </auto-generated>
#nullable enable

using SealedFga.AuthModel;
using SealedFga;

namespace TestApp;

/// <summary>
///     Represents a set of strongly-typed SealedFGA relations for the SecretEntityIdGroups entity.
/// </summary>
public class SecretEntityIdGroups(string val)
: SealedFgaRelation(val), ISealedFgaRelation<SecretEntityId>
{
    /// <summary>The <c>OwnedBy</c> relation.</summary>
    public static readonly SecretEntityIdGroups OwnedBy = new SecretEntityIdGroups("OwnedBy");


    /// <summary>
    ///     Creates a <see cref="SecretEntityIdGroups"/> from an OpenFGA relation string.
    /// </summary>
    /// <param name="openFgaString">The OpenFGA relation string.</param>
    /// <returns>A new <see cref="SecretEntityIdGroups"/> instance.</returns>
    public static SecretEntityIdGroups FromOpenFgaString(string openFgaString) => new SecretEntityIdGroups(openFgaString);
}