//HintName: AgencyEntityId.partial.g.cs
// <auto-generated>
//     This file was generated by SealedFga. Do not edit it directly.
// </auto-generated>
#nullable enable

using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SealedFga.AuthModel;
using SealedFga.Util;
using System.ComponentModel;
using System.Text.Json.Serialization;
using System;

namespace TestApp;


[TypeConverter(typeof(IdTypeConverter))]
[JsonConverter(typeof(IdJsonConverter))]
public partial class AgencyEntityId : ISealedFgaTypeId<AgencyEntityId>, IEquatable<AgencyEntityId>
{
    /// <summary>
    ///     The ID's value.
    /// </summary>
    public Guid Value { get; set; }

    /// <summary>
    ///     Creates a new instance of AgencyEntityId from the ID's "raw" type.
    /// </summary>
    /// <param name="val">The raw ID's value.</param>
    public AgencyEntityId(Guid val)
    {
        Value = val;
    }

    /// <inheritdoc />
    public static string OpenFgaTypeName => "agency";

    /// <summary>
    ///     Creates a new instance of <see cref="AgencyEntityId"/> with a generated value.
    /// </summary>
    public static AgencyEntityId New()
    {
        return new AgencyEntityId(Guid.NewGuid());
    }

    /// <inheritdoc />
    public static AgencyEntityId Parse(string val)
    {
        return new AgencyEntityId(Guid.Parse(val));
    }

    /// <inheritdoc />
    public string AsOpenFgaIdTupleString()
        => $"{OpenFgaTypeName}:{ToString()}";

    /// <inheritdoc />
    public override string ToString()
    {
        return Value.ToString();
    }

    /// <inheritdoc />
    public override bool Equals(object? obj)
    {
        if (ReferenceEquals(null, obj)) return false;
        if (ReferenceEquals(this, obj)) return true;
        if (obj.GetType() != this.GetType()) return false;
        return Equals((AgencyEntityId) obj);
    }

    /// <inheritdoc />
    public bool Equals(AgencyEntityId? other)
    {
        if (ReferenceEquals(null, other)) return false;
        if (ReferenceEquals(this, other)) return true;
        return Value.Equals(other.Value);
    }

    /// <inheritdoc />
    public override int GetHashCode()
    {
        return Value.GetHashCode();
    }

    public static bool operator ==(AgencyEntityId? left, AgencyEntityId? right)
    {
        if (ReferenceEquals(left, null))
        {
            return ReferenceEquals(right, null);
        }

        return left.Equals(right);
    }

    public static bool operator !=(AgencyEntityId? left, AgencyEntityId? right)
    {
        return !(left == right);
    }


    /// <summary>
    ///     Converts a <see cref="AgencyEntityId" /> to a <see cref="Guid" /> and vice versa for DB storage.
    /// </summary>
    public class EfCoreValueConverter() : ValueConverter<AgencyEntityId, Guid>(
        id => id.Value,
        val => new AgencyEntityId(val));

    /// <summary>
    ///    Converts a <see cref="AgencyEntityId" /> to its JSON representation and vice versa.
    /// </summary>
    public class IdJsonConverter() : JsonSimpleStringConverter<AgencyEntityId>(s => AgencyEntityId.Parse(s));

    /// <summary>
    ///    Converts a <see cref="AgencyEntityId" /> to another compatible type and vice versa.
    /// </summary>
    public class IdTypeConverter() : GuidIdTypeConverter<AgencyEntityId>(g => new AgencyEntityId(g), s => AgencyEntityId.Parse(s));
}