using System.Collections.Generic;
using System.Linq;

namespace SealedFga.Models;

public class GeneratedFile(
    string fileName,
    string fileContent,
    ISet<string>? usings = null,
    string namespaceName = Settings.PackageNamespace
) {
    private const string TopFileComment =
        """
        // <auto-generated>
        //     This file was generated by SealedFga. Do not edit it directly.
        // </auto-generated>
        #nullable enable


        """;

    public string FileName { get; } = fileName;
    public ISet<string> Usings { get; } = usings ?? new HashSet<string>();
    public string FileContent { get; } = fileContent;

    public string BuildFullFileContent()
        => TopFileComment
           + Usings.Select(u => $"using {u};\n")
                   .Aggregate("", (acc, u) => acc + u)
           + $"\nnamespace {namespaceName};\n\n"
           + FileContent;
}
